taskapp/taskapp/Models/ErrorViewModel.cs
using System;

namespace taskapp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

taskapp/taskapp/Models/TaskItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace taskapp.Models
{
    public class TaskItem
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}

taskapp/taskapp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using taskapp.Models;

namespace taskapp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

taskapp/taskapp/Controllers/TaskItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using taskapp.Data;
using taskapp.Models;

namespace taskapp.Controllers
{
    public class TaskItemsController : Controller
    {
        private readonly AppDbContext _context;

        public TaskItemsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: TaskItems
        public async Task<IActionResult> Index()
        {
            return View(await _context.Tasks.ToListAsync());
        }

        // GET: TaskItems/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var taskItem = await _context.Tasks
                .FirstOrDefaultAsync(m => m.ID == id);
            if (taskItem == null)
            {
                return NotFound();
            }

            return View(taskItem);
        }

        // GET: TaskItems/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TaskItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Title,Description")] TaskItem taskItem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(taskItem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(taskItem);
        }

        // GET: TaskItems/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var taskItem = await _context.Tasks.FindAsync(id);
            if (taskItem == null)
            {
                return NotFound();
            }
            return View(taskItem);
        }

        // POST: TaskItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Title,Description")] TaskItem taskItem)
        {
            if (id != taskItem.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(taskItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TaskItemExists(taskItem.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(taskItem);
        }

        // GET: TaskItems/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var taskItem = await _context.Tasks
                .FirstOrDefaultAsync(m => m.ID == id);
            if (taskItem == null)
            {
                return NotFound();
            }

            return View(taskItem);
        }

        // POST: TaskItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var taskItem = await _context.Tasks.FindAsync(id);
            _context.Tasks.Remove(taskItem);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TaskItemExists(int id)
        {
            return _context.Tasks.Any(e => e.ID == id);
        }
    }
}

taskapp/taskapp/Views/Home/Index.cshtml
@model taskapp.Models.TaskItem 

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4 text-center">Welcome</h1>
</div>
<hr />
<div class="container">
    <div class="col">
        <form asp-action="Create" asp-controller="TaskItems" method="post" class="mt-3">
            <div asp-validation-summary="All" class="text-danger">
            </div>
            <div class="form-group">
                <label asp-for="Title"></label>
                <div class="">
                    <input asp-for="Title" class="form-control">
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <div class="">
                    <input asp-for="Description" class="form-control">
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="text-right">
                    <button type="submit" class="btn btn-outline-dark" style="width:auto">
                        Create New Task
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>


<div class="text-right container">
    <a class="nav-link text-dark" asp-area="" asp-controller="TaskItems" asp-action="Index">My Tasks</a>
</div>

taskapp/taskapp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - taskapp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Task List</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TaskItems" asp-action="Index">My Tasks</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - taskapp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

taskapp/taskapp/Views/TaskItems/Create.cshtml
@model taskapp.Models.TaskItem

@{
    ViewData["Title"] = "Create";
}

<div class="text-center">
    <h2 class="display-4">Create Task</h2>
</div>
<hr />
<div class="row">
    <div class="col">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group text-right">
                <input type="submit" value="Create" class="btn btn-outline-dark" />
            </div>
        </form>
    </div>
</div>

<div class="text-right">
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

taskapp/taskapp/Views/TaskItems/Delete.cshtml
@model taskapp.Models.TaskItem

@{
    ViewData["Title"] = "Delete";
}

<div class="text-center">
    <h2 class="display-4">Delete Task</h2>
</div>
<div>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <dl class="row">
                <dd class="mt-3">
                    <h3><b>@Html.DisplayFor(model => model.Title)</b></h3>
                </dd>
            </dl>
            <dl class="row">
                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>
            </dl>
        </div>
    </div>
</div>

<div class="text-right">
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-outline-danger" />
    </form>
</div>

<div class="text-right mt-3">
    <a asp-action="Index">Back to List</a>
</div>

taskapp/taskapp/Views/TaskItems/Details.cshtml
@model taskapp.Models.TaskItem

@{
    ViewData["Title"] = "Details";
}

<div class="text-center">
    <h2 class="display-4">Details</h2>
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <dl class="row">
            <dd class="mt-3">
                <h4><b>@Html.DisplayFor(model => model.Title)</b></h4>
            </dd>
        </dl>
        <dl class="row">
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
        </dl>
    </div>
</div>

<div class="text-right mt-3">
    <a asp-action="Edit" asp-route-id="@Model.ID" class="btn btn-outline-dark">Edit</a>
</div>
<div class="text-right mt-3">
    <a asp-action="Index">Back to List</a>
</div>

taskapp/taskapp/Views/TaskItems/Edit.cshtml
@model taskapp.Models.TaskItem

@{
    ViewData["Title"] = "Edit";
}

<div class="text-center">
    <h2 class="display-4">Edit Task</h2>
</div>
<hr />
<div class="row">
    <div class="col">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group text-right">
                    <input type="submit" value="Save" class="btn btn-outline-dark" />
            </div>
        </form>
    </div>
</div>

<div class="text-right">
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

taskapp/taskapp/Views/TaskItems/Index.cshtml
@model IEnumerable<taskapp.Models.TaskItem>

@{
    ViewData["Title"] = "Index";
}


<div class="text-center">
    <h2 class="display-4">My Tasks</h2>
</div>

<hr />
<table class="table table-borderless">
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <b>@Html.DisplayFor(modelItem => item.Title)</b>
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td class="text-right">
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="text-right">
    <a asp-action="Create" class="btn btn-outline-dark">Create New Task</a>
</div>